# ============================================================================
# Browser Security Hardening Script (Firefox & Chrome)
# ============================================================================
# This script hardens Firefox and Chrome browsers with security best practices
# including privacy settings, extension management, and secure configurations.
#
# Requirements: Administrator privileges (for some settings)
# Usage: .\browser-hardening.ps1 [-Firefox] [-Chrome] [-All]
# ============================================================================

param(
    [switch]$Firefox,
    [switch]$Chrome,
    [switch]$All
)

$ErrorActionPreference = "Continue"
$LogFile = "browser-hardening-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $LogMessage = "[$Timestamp] [$Level] $Message"
    Write-Host $LogMessage
    Add-Content -Path $LogFile -Value $LogMessage
}

# If -All is specified, enable both browsers
if ($All) {
    $Firefox = $true
    $Chrome = $true
}

# If no browser specified, configure both
if (-not ($Firefox -or $Chrome)) {
    $Firefox = $true
    $Chrome = $true
}

Write-Log "Starting Browser Hardening..." "INFO"

# ============================================================================
# Firefox Hardening
# ============================================================================
if ($Firefox) {
    Write-Log "Hardening Firefox..." "INFO"
    
    # Firefox preferences are stored in prefs.js and user.js files
    # Location: %APPDATA%\Mozilla\Firefox\Profiles\<profile>\prefs.js
    
    $firefoxProfiles = Get-ChildItem "$env:APPDATA\Mozilla\Firefox\Profiles" -Directory -ErrorAction SilentlyContinue
    
    if ($firefoxProfiles) {
        foreach ($profile in $firefoxProfiles) {
            $prefsFile = Join-Path $profile.FullName "prefs.js"
            $userJsFile = Join-Path $profile.FullName "user.js"
            
            Write-Log "Configuring Firefox profile: $($profile.Name)" "INFO"
            
            # Create user.js file with security settings (overrides prefs.js)
            $firefoxSettings = @"
// Firefox Security Hardening Configuration
// Generated by Cybersecurity Hardening Toolkit

// Privacy & Tracking Protection
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
user_pref("privacy.trackingprotection.cryptomining.enabled", true);

// Disable Telemetry
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.server", "");
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);

// Disable Location Services
user_pref("geo.enabled", false);

// Disable WebRTC (prevents IP leak)
user_pref("media.peerconnection.enabled", false);

// HTTPS Only Mode
user_pref("dom.security.https_only_mode", true);
user_pref("dom.security.https_only_mode_ever_enabled", true);

// Disable Password Saving (use password manager instead)
user_pref("signon.rememberSignons", false);

// Disable Form Autofill
user_pref("browser.formfill.enable", false);

// Disable Search Suggestions
user_pref("browser.search.suggest.enabled", false);

// Enable Do Not Track
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.donottrackheader.value", 1);

// Disable Safe Browsing (optional - can impact security, but improves privacy)
// user_pref("browser.safebrowsing.malware.enabled", false);
// user_pref("browser.safebrowsing.phishing.enabled", false);

// Disable Pocket
user_pref("extensions.pocket.enabled", false);

// Disable Studies
user_pref("app.shield.optoutstudies.enabled", false);

// Clear data on close
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("privacy.clearOnShutdown.downloads", true);
user_pref("privacy.clearOnShutdown.formData", true);
user_pref("privacy.clearOnShutdown.history", true);
user_pref("privacy.clearOnShutdown.sessions", true);

// Disable DRM (optional)
// user_pref("media.eme.enabled", false);

// Disable WebGL (optional - can break some sites)
// user_pref("webgl.disabled", true);

// Disable JavaScript (optional - breaks most sites, use with caution)
// user_pref("javascript.enabled", false);
"@
            
            try {
                Set-Content -Path $userJsFile -Value $firefoxSettings -Force
                Write-Log "Firefox security settings applied to profile: $($profile.Name)" "SUCCESS"
            } catch {
                Write-Log "Failed to configure Firefox profile $($profile.Name) : $_" "ERROR"
            }
        }
    } else {
        Write-Log "Firefox profiles not found. Firefox may not be installed." "WARNING"
    }
}

# ============================================================================
# Chrome Hardening
# ============================================================================
if ($Chrome) {
    Write-Log "Hardening Chrome..." "INFO"
    
    # Chrome preferences are stored in Preferences file
    # Location: %LOCALAPPDATA%\Google\Chrome\User Data\Default\Preferences
    
    $chromeUserData = "$env:LOCALAPPDATA\Google\Chrome\User Data"
    
    if (Test-Path $chromeUserData) {
        $chromeProfiles = Get-ChildItem $chromeUserData -Directory -Filter "Profile*" -ErrorAction SilentlyContinue
        $defaultProfile = Join-Path $chromeUserData "Default"
        
        $profilesToConfigure = @()
        if (Test-Path $defaultProfile) {
            $profilesToConfigure += $defaultProfile
        }
        $profilesToConfigure += $chromeProfiles | ForEach-Object { $_.FullName }
        
        foreach ($profilePath in $profilesToConfigure) {
            $prefsFile = Join-Path $profilePath "Preferences"
            
            if (Test-Path $prefsFile) {
                Write-Log "Configuring Chrome profile: $profilePath" "INFO"
                
                try {
                    # Read existing preferences
                    $prefs = Get-Content $prefsFile -Raw | ConvertFrom-Json
                    
                    # Security and Privacy Settings
                    if (-not $prefs.profile) { $prefs | Add-Member -MemberType NoteProperty -Name "profile" -Value @{} }
                    if (-not $prefs.profile.content_settings) { $prefs.profile.content_settings = @{} }
                    if (-not $prefs.profile.content_settings.exceptions) { $prefs.profile.content_settings.exceptions = @{} }
                    
                    # Disable location services
                    if (-not $prefs.profile.content_settings.exceptions.geolocation) {
                        $prefs.profile.content_settings.exceptions.geolocation = @{}
                    }
                    
                    # Disable notifications
                    if (-not $prefs.profile.content_settings.exceptions.notifications) {
                        $prefs.profile.content_settings.exceptions.notifications = @{}
                    }
                    
                    # Privacy settings
                    if (-not $prefs.privacy) { $prefs | Add-Member -MemberType NoteProperty -Name "privacy" -Value @{} }
                    $prefs.privacy | Add-Member -MemberType NoteProperty -Name "network_prediction_options" -Value 2 -Force  # Disable network prediction
                    
                    # Disable password saving
                    if (-not $prefs.profile.password_manager) { $prefs.profile.password_manager = @{} }
                    $prefs.profile.password_manager.enabled = $false
                    
                    # Disable autofill
                    if (-not $prefs.autofill) { $prefs | Add-Member -MemberType NoteProperty -Name "autofill" -Value @{} }
                    $prefs.autofill.profile_enabled = $false
                    
                    # Disable search suggestions
                    if (-not $prefs.search) { $prefs | Add-Member -MemberType NoteProperty -Name "search" -Value @{} }
                    $prefs.search.suggest_enabled = $false
                    
                    # Save preferences
                    $prefs | ConvertTo-Json -Depth 100 | Set-Content $prefsFile -Force
                    Write-Log "Chrome security settings applied to profile: $profilePath" "SUCCESS"
                    
                } catch {
                    Write-Log "Failed to configure Chrome profile $profilePath : $_" "ERROR"
                }
            }
        }
        
        # Chrome Group Policy (if available)
        # Chrome policies can be set via registry for enterprise management
        Write-Log "Applying Chrome Group Policy settings..." "INFO"
        try {
            $chromePolicyPath = "HKLM:\SOFTWARE\Policies\Google\Chrome"
            if (-not (Test-Path $chromePolicyPath)) {
                New-Item -Path $chromePolicyPath -Force | Out-Null
            }
            
            # Enable Safe Browsing
            Set-ItemProperty -Path $chromePolicyPath -Name "SafeBrowsingProtectionLevel" -Value 1 -ErrorAction SilentlyContinue
            
            # Disable password saving
            Set-ItemProperty -Path $chromePolicyPath -Name "PasswordManagerEnabled" -Value 0 -ErrorAction SilentlyContinue
            
            # Enable Do Not Track
            Set-ItemProperty -Path $chromePolicyPath -Name "EnableDoNotTrack" -Value 1 -ErrorAction SilentlyContinue
            
            Write-Log "Chrome Group Policy settings applied" "SUCCESS"
        } catch {
            Write-Log "Failed to apply Chrome Group Policy: $_" "WARNING"
        }
        
    } else {
        Write-Log "Chrome user data directory not found. Chrome may not be installed." "WARNING"
    }
}

Write-Log "Browser Hardening completed!" "SUCCESS"
Write-Host "`nBrowser hardening completed. Review the log file for details." -ForegroundColor Green
Write-Host "Note: Some settings may require browser restart to take effect." -ForegroundColor Yellow

